"""Init

Revision ID: 30612ec15caf
Revises: 
Create Date: 2021-03-20 00:20:03.042440

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '30612ec15caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'dealer',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('name', sa.String(), nullable=True),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_table(
		'car',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('brand', sa.String(), nullable=True),
		sa.Column('model', sa.String(), nullable=True),
		sa.Column('price', sa.Integer(), nullable=True),
		sa.Column('dealer_id', sa.Integer(), nullable=True),
		sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
		sa.PrimaryKeyConstraint('id')
	)


# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('car')
	op.drop_table('dealer')
# ### end Alembic commands ###
